create extension if not exists pgcrypto;

create table if not exists public.restaurant_settings (
    id integer primary key default 1 check (id = 1),
    restaurant_name text not null default 'La Mafia dei Dolci',
    whatsapp text not null default '',
    updated_at timestamptz not null default now()
);

create table if not exists public.menu_items (
    id bigint primary key,
    category text not null,
    name text not null,
    description text not null default '',
    price numeric(10, 2) not null default 0,
    image text not null default '',
    sort_order integer not null default 0,
    updated_at timestamptz not null default now()
);

create table if not exists public.orders (
    id bigint generated by default as identity primary key,
    customer_name text not null,
    table_number text not null,
    notes text not null default '',
    status text not null default 'novo' check (status in ('novo', 'em_preparo', 'pronto', 'entregue', 'cancelado')),
    total numeric(10, 2) not null default 0,
    item_count integer not null default 0,
    created_at timestamptz not null default now()
);

create table if not exists public.order_items (
    id bigint generated by default as identity primary key,
    order_id bigint not null references public.orders(id) on delete cascade,
    item_id bigint,
    name text not null,
    quantity integer not null,
    unit_price numeric(10, 2) not null,
    subtotal numeric(10, 2) not null
);

insert into public.restaurant_settings (id, restaurant_name, whatsapp)
values (1, 'La Mafia dei Dolci', '')
on conflict (id) do nothing;

alter table public.restaurant_settings enable row level security;
alter table public.menu_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "Public can read restaurant settings" on public.restaurant_settings;
create policy "Public can read restaurant settings"
on public.restaurant_settings
for select
using (true);

drop policy if exists "Authenticated users can manage restaurant settings" on public.restaurant_settings;
create policy "Authenticated users can manage restaurant settings"
on public.restaurant_settings
for all
to authenticated
using (true)
with check (true);

drop policy if exists "Public can read menu items" on public.menu_items;
create policy "Public can read menu items"
on public.menu_items
for select
using (true);

drop policy if exists "Authenticated users can manage menu items" on public.menu_items;
create policy "Authenticated users can manage menu items"
on public.menu_items
for all
to authenticated
using (true)
with check (true);

drop policy if exists "Public can read orders" on public.orders;
create policy "Public can read orders"
on public.orders
for select
using (true);

drop policy if exists "Public can create orders" on public.orders;
create policy "Public can create orders"
on public.orders
for insert
to anon, authenticated
with check (true);

drop policy if exists "Authenticated users can update orders" on public.orders;
create policy "Authenticated users can update orders"
on public.orders
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Public can read order items" on public.order_items;
create policy "Public can read order items"
on public.order_items
for select
using (true);

drop policy if exists "Public can create order items" on public.order_items;
create policy "Public can create order items"
on public.order_items
for insert
to anon, authenticated
with check (true);

insert into storage.buckets (id, name, public)
values ('menu-images', 'menu-images', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "Public can view menu images" on storage.objects;
create policy "Public can view menu images"
on storage.objects
for select
using (bucket_id = 'menu-images');

drop policy if exists "Authenticated users can upload menu images" on storage.objects;
create policy "Authenticated users can upload menu images"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'menu-images');

drop policy if exists "Authenticated users can update menu images" on storage.objects;
create policy "Authenticated users can update menu images"
on storage.objects
for update
to authenticated
using (bucket_id = 'menu-images')
with check (bucket_id = 'menu-images');

drop policy if exists "Authenticated users can delete menu images" on storage.objects;
create policy "Authenticated users can delete menu images"
on storage.objects
for delete
to authenticated
using (bucket_id = 'menu-images');
